# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-30 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20180329_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
